version: '3.8'

services:

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - node-name=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: {}
  kibanadata: {}
